### ISSUE TITLE
Adding WFCatalog to routing

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/routing#13]
Hi Javier, hope you are doing well. It would be nice to add the WFCatalog to the routing service. I can help with the implementation if you can point me to the routines where services are resolved.

Here are five addresses of running catalogues:

    $nodesWFCatalog = (object) Array (
      "ODC" => "http://www.orfeus-eu.org/eidaws/wfcatalog/alpha",
      "NOA" => "http://eida.gein.noa.gr/eidaws/wfcatalog/alpha",
      "INGV" => "catalog.data.ingv.it/wfcatalog/1",
      "BGR" => "http://eida.bgr.de/wfcatalog/alpha",
      "GFZ" => "http://geofon.gfz-potsdam.de/eidaws/wfcatalog/alpha"
    );

Best,
Mathijs

**Comment by javiquinte** [comment]
Hi Mathijs!
There is actually no code to change. Every node administrator/operator should update the configuration file and the Routing Service will include the routes automatically.
I've been updated our configuration during the last two days and is now ready. The other four nodes with a running instance of WFCatalog should do the same.
I paste below a real example of a route entry:

```
<ns0:route networkCode="Z3" stationCode="A015A" locationCode="*" streamCode="*">
    <ns0:station address="http://geofon.gfz-potsdam.de/fdsnws/station/1/query" priority="1" start="2015-09-07T00:00:00" end="2020-07-01T00:00:00" />
    <ns0:wfcatalog address="http://geofon.gfz-potsdam.de/eidaws/wfcatalog/alpha/query" priority="1" start="2015-09-07T00:00:00" end="2020-07-01T00:00:00" />
    <ns0:dataselect address="http://geofon.gfz-potsdam.de/fdsnws/dataselect/1/query" priority="1" start="2015-09-07T00:00:00" end="2020-07-01T00:00:00" />
</ns0:route>```

I will send a mail to eida_maint to clarify this.

**Comment by Jollyfant** [comment]
I see that explains why routing for WFCatalog only worked for GFZ. Nice!
