### ISSUE TITLE
Prepare Beta1 of v1.1.0

### ISSUE THREAD

**Issue by javiquinte** [EIDA/routing#23]
- Update version numbers
- Review documentation
- Contact beta-testers

**Comment by javiquinte** [comment]
Version numbers updated and documentation also.

**Comment by javiquinte** [comment]
@nikosT and @Jollyfant Could you take a look at this release in the following URL?

http://rz-vm258.gfz-potsdam.de/eidaws/routing/nightly/query

Thanks!

**Comment by Jollyfant** [comment]
Cool Javier! I will have a look and try some queries.

**Comment by Jollyfant** [comment]
Tried some queries, couldn't find a problem. Nice work 👍

**Comment by nikosT** [comment]
Hi,
I made a query like this: [http://rz-vm258.gfz-potsdam.de/eidaws/routing/nightly/query?sta=A*](http://rz-vm258.gfz-potsdam.de/eidaws/routing/nightly/query?sta=A*)
Is it OK to have: `<sta>A*</sta>` ?

**Comment by Jollyfant** [comment]
It seems fine to include a wildcard IMHO.

**Comment by javiquinte** [comment]
Update documentation with instructions for virtual networks definition and what to expect from the queries.
