### ISSUE TITLE
Alternate input at test/testService.py

### ISSUE THREAD

**Issue by nikosT** [EIDA/routing#33]
Suggestion for input at test/testService.py.
if no args:
read baseURL variable from routing.cfg (default)
else:
read args

eg.1
`./testService.py`
(reads baseURL from routing.cfg)

eg.2
`./testService.py url`
(reads url)

**Comment by javiquinte** [comment]
Sure, @nikosT !
Feel free to add your suggestion.

**Comment by javiquinte** [comment]
Implemented since commit 024bbcb1e798b0834c908f6ce0a15ce30fc70fb6
