### ISSUE TITLE
POST 500

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/routing#34]
Hi Javier, I installed the new WebDC 3 and made a request for FDSN-Station but it broke routing:

req.txt:

    service=station
    format=json
    NL OPLO -- BHE 2007-05-01T00:00:00.0000Z 2017-05-23T23:59:59.0000Z
    NL VKB -- BHE 2007-05-01T00:00:00.0000Z 2017-05-23T23:59:59.0000Z
    NL WIT -- BHE 2007-05-01T00:00:00.0000Z 2017-05-23T23:59:59.0000Z

curl -X POST -d req.txt http://geofon.gfz-potsdam.de/eidaws/routing/1/query

and the service returns an internal service error.

**Comment by javiquinte** [comment]
Fixed in commit a5ece761c1a73fdb897b67dcce93387e10d3f058
In any case, test it with
`
wget --post-file=req.txt "http://rz-vm258.gfz-potsdam.de/eidaws/routing/nightly/query"
`
because `curl` seems to create problems with the newline chars. :-(

**Comment by feuchner** [comment]
With curl, you have to use the --data-binary option instead of -d.
