### ISSUE TITLE
all user configuration inside routing.cfg

### ISSUE THREAD

**Issue by nikosT** [EIDA/routing#45]
I suggest that the path inside `routing.wsgi` file should be a variable that is being read by the `routing.cfg` file, so that the user would need to configure only a particular file (`routing.cfg`).

**Comment by javiquinte** [comment]
Being implemented in branch issuewsgi

**Comment by Jollyfant** [comment]
Yeah nice idea Niko. I forgot to do this when updating to 1.1.1 initially.

**Comment by javiquinte** [comment]
Even better. Automatically recognized by the location of the WSGI file.
Implemented since commit 869f61678ee57daa51b92bb244c97e53b03f53c1
