### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/routing#51]
Hi Javier, it seems the routing only works with Python3 now. Is that correct? When trying to run it says:

Cannot import module request `urllib.request`. This changes a lot of the installation procedures since you need mod_wsgi for Python3.

M

**Comment by Jollyfant** [comment]
Fyi this is for fresh installation from master.

**Comment by javiquinte** [comment]
There is yet no official release, but there will be. You could install the last release (python2).
Or you could install the mod-wsgi for py3 and it should work out of the box.

Am 13. Februar 2018 10:54:41 MEZ schrieb Jollyfant <notifications@github.com>:
>Hi Javier, it seems the routing only works with Python3 now. Is that
>correct? When trying to run it says:
>
>Cannot import module request `urllib.request`. This changes a lot of
>the installation procedures since you need mod_wsgi for Python3.
>
>M
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/EIDA/routing/issues/51

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Jollyfant** [comment]
Thanks it works with mod-wsgi-py3.
