### ISSUE TITLE
Support distributed provision of the additional node information and remove hard-coded info

### ISSUE THREAD

**Issue by nikosT** [EIDA/routing#67]
Move the hard-coded node information provided at the ```routeutils/utils.py``` to the respective fields of the ```routing.xml``` local information.

For instance, the below hard-coded information:
```"name": "NOA",
        "website": "http://www.noa.gr",
        "fullName": "NOA Data Centre",
        "summary": "National Observatory of Athens",
        "repositories": [
            {
                "name": "archive",
                "description": "Archive of continuous seismological data",
                "website": "http://bbnet.gein.noa.gr",
                "services": [
                    {
                        "name": "fdsnws-dataselect-1",
                        "description": "Access to raw time series data",
                        "url": "http://eida.gein.noa.gr/fdsnws/dataselect/1/"
                    },
                    {
                        "name": "fdsnws-station-1",
                        "description": "Access to metadata describing raw time series data",
                        "url": "http://eida.gein.noa.gr/fdsnws/station/1/"
                    },
                    {
                        "name": "eidaws-wfcatalog",
                        "description": "EIDA WFCatalog service",
                        "url": "http://eida.gein.noa.gr/eidaws/wfcatalog/1/"
                    }
                ],
```

Could be provided in a distributed way where each node would be responsible for the info served:
   
```<ns0:routing>
<ns0:name>NOA</ns0:name>
<ns0:website>http://www.noa.gr</ns0:website>
<ns0:fullName>NOA Data Centre</ns0:fullName>
<ns0:summary>National Observatory of Athens</ns0:summary>
<ns0:route networkCode="CQ" stationCode="*" locationCode="*" streamCode="*">
<ns0:station address="http://eida2.gein.noa.gr/fdsnws/station/1/query" priority="1" start="2013-01-01T00:00:00" end="" description="Access to metadata describing raw time series data"/>
<ns0:dataselect address="http://eida2.gein.noa.gr/fdsnws/dataselect/1/query" priority="1" start="2013-01-01T00:00:00" end="" description="Access to raw time series data"/>
<ns0:wfcatalog address="http://eida2.gein.noa.gr/eidaws/wfcatalog/1/query" priority="1" start="2013-01-01T00:00:00" end="" description="EIDA WFCatalog service"/>
</ns0:route>
```

Moreover, the ```/endpoints``` method could provide some of the information (e.g. name, summary, etc.) along with the URL to the routing.xml file.

**Comment by damb** [comment]
Removing hardcoded, redundant settings from the codebase is IMO always a good idea. This will allow us to move to a setup where the concept of a DC is defined by a single URL i.e. the URL to the `eidaws-routing` `localconfig` configuration file. Also, the location the URL is pointing to, could basically be anywhere which BTW gives us another *degree of freedom*.

However, since the definition of the `localconfig` gets progressively richer I'd opt for having an appropriate `localconfig` schema. Any opinions on that? (There was already a discussion on `eida_maint` a few month ago ...)

**Comment by nikosT** [comment]
@damb I also agree that a schema would be necessary! One thought, though; we should not complicate it a lot, otherwise, it might be unflexible to maintain it and even the processing might become a great overhead.

**Comment by damb** [comment]
> One thought, though; we should not complicate it a lot, otherwise, it might be unflexible to maintain it and even the processing might become a great overhead.

Agreed. Since it is mainly intended for validation and the `localconfig` configuration of DCs is rather small in size I don't think that *processing time* is critical.

**Comment by javiquinte** [comment]
Done since version 1.2.2
