### ISSUE TITLE
skip problematic files

### ISSUE THREAD

**Issue by nikosT** [EIDA/routing#69]
Adding Routes should skip problematic files returning a coherent version of the routes.

**Comment by nikosT** [comment]
The https://github.com/EIDA/routing/pull/70 tested in EIDA node and seems to be working. However, no error message appears in the output of the ./updateAll.py.

**Comment by javiquinte** [comment]
PR merged in commit e9101c8a41c57142aa70cf5884cab5b111a3522d

**Comment by javiquinte** [comment]
Add improvement. If a previous copy exists, replace the wrong file with the old one.
