### ISSUE TITLE
network startdate vs station startdate in routing

### ISSUE THREAD

**Issue by kbouk** [EIDA/routing#77]
Hello,

I noticed that if the station startdate is before the network startdate, then routing returns the network start date, instead of the station.
Is this intended ? Maybe a station could exist before the network started.
For example for station HA.ATHU:
https://eida.gein.noa.gr/fdsnws/station/1/query?net=HA&station=ATHU&channel=???&level=response
Network Start Date: 2008-01-01T00:00:00
Station Start Date: 2007-01-17T00:00:00

Routing returns the Network start time:
HA ATHU * * 2008-01-01T00:00:00 2022-11-03

Is this something that must be corrected in routing or in the metadata?

**Comment by javiquinte** [comment]
I would say that the metadata is inconsistent. All entities in deeper levels should be encompassed in the time frame of the one above. Network <= station <= channel

**Comment by kbouk** [comment]
Ok. I'll leave some days this issue open, if someone have any more comments and then i'll close it.
