### ISSUE TITLE
Add globalconfig to wadl

### ISSUE THREAD

**Issue by kaestli** [EIDA/routing#83]
I'd suggest to add /eidaws/routing/1/globalconfig and its (mandatory and optional) parameters to https://geofon.gfz-potsdam.de/eidaws/routing/1/application.wadl

**Comment by javiquinte** [comment]
Good point, Philipp!

**Comment by javiquinte** [comment]
Added in commit 48ec6aa16bdb8a226de3233ff54c8e18cd7af52a
